### ISSUE TITLE
Big Lifts Layout

### ISSUE THREAD

**Issue by afrohorse02** [JuricaRT/fitness_tracker#10]
![layout big lfits](https://user-images.githubusercontent.com/61162442/91474404-75f7c080-e89a-11ea-9437-f7d108c82b4e.PNG)
Potrebna ideja za prazan dio u dolje desnom kutu
Lift history je lista koja se updatea svaki put kad se pritisne gumb save pri updateanju big liftova, lift se moze izbrisati u slucaju pogreske ili sl.

**Comment by JuricaRT** [comment]
Vidio sam layout, moram jos razmislit kak bi ja to poslozio i kaj bi islo dolje desno

**Comment by JuricaRT** [comment]
![D44dc91e7539a2225af26d4cedf19ca7c](https://user-images.githubusercontent.com/57286068/91481679-14891f00-e8a5-11ea-923a-7ba37e848d0f.png)

- Ako ne postoji niti jedan zapisani lift u one rep max lifts ili u lifts for reps Update gumb ce postat Add, ali ce otvarat isti prozor

- X kod liftova u lift history brisu taj zapisani lift

- clear gumb brise sve zapisane liftove, samo vrijednosti a ne i preferred lifts

- nema headera, to je prijedlog i za ostale layoute

- graf prikazuje sve one rep max preferred liftove, nesto kao ovaj graf dolje

![multiple-line-graph-excel](https://user-images.githubusercontent.com/57286068/91482884-0dfba700-e8a7-11ea-984f-2ea4b20fa6e2.png)
