### ISSUE TITLE
Body Fat Calculator

### ISSUE THREAD

**Issue by JuricaRT** [JuricaRT/fitness_tracker#11]
Isti layout kao i one rep max, samo kalkulator i tablica kao sto je na ovoj stranici: [https://www.calculator.net/body-fat-calculator.html?ctype=metric&csex=m&cage=25&cweightlbs=152&cheightfeet=5&cheightinch=10.5&cneckfeet=1&cneckinch=7.5&cwaistfeet=3&cwaistinch=1.5&chipfeet=2&chipinch=10.5&cweightkgs=70&cheightmeter=178&cneckmeter=50&cwaistmeter=96&chipmeter=92&x=57&y=16](url)

**Comment by afrohorse02** [comment]
Ok je.
