### ISSUE TITLE
Workout Notes Layout

### ISSUE THREAD

**Issue by JuricaRT** [JuricaRT/fitness_tracker#12]

**Comment by JuricaRT** [comment]
![Workout_notes](https://user-images.githubusercontent.com/57286068/91629496-e4876c00-e9c9-11ea-90e3-1a7702fcb1f2.png)
![Workout_notes_Copy](https://user-images.githubusercontent.com/57286068/91629502-e8b38980-e9c9-11ea-99f7-a701462316e3.png)

Ovo je sto ja mislim da bi trebalo bit u ovim layoutima, treba smislit My Workouts layout i jos nesto dodat/izmijenit na ovim layoutima

**Comment by JuricaRT** [comment]
![D2e4ab3be8bbd5758380432c351b6a672](https://user-images.githubusercontent.com/57286068/92322518-015b1980-f032-11ea-825f-bc036adc1eb7.png)

- Korisnik moze "postavit" trenutni workout plan kojeg sam moze napravit
- Svaki workout plan ima odredeni broj dana u tjednu
- Na kalendaru moze oznacavat da li je odradio workout taj odredeni dan
- Korisnik moze mijenjat workout plan, za svaki workout plan postoji neka posebna boja na kalendaru, kad promjeni plan na kalendaru ostaju oznaceni prijasnji workouti s nekom bojom, ovaj novi dobiva drugu boju
- Workout planovi se mogu kasnije koristit u grafovima, tamo mozemo pokazat napredak korisnika tijekom svakog programa i sl.

### My Workouts
- korisnik ovdje dodaje/brise/ureduje svoje workout planove
- klikom na neki workout otvara se prozor za uredivanje workouta
- add workout gumb otvara prozor za kreiranje workouta
- workout se brisem pritiskom na gumb, ovdje pritiskom na X

### Exercises
- korisnik ovdje moze pogledat pojedine vjezbe, ovdje su vjezbe podijeljne u kategorije, korisnik moze kliknut na neku kategoriju
- klikom na kategoriju otvara se prozor te kategorije, tu moze pretrazivat vjezbe u bazi (search bar) i moze odabrat neku vjezbu
- svaka vjezba ima svoj poseban prozor, tamo se nalaze neki podaci o toj vjezbi
- npr. slika vjezbe, opcenito o vjezbi koje misice pogada, kako se izvodi i sl.

**Comment by afrohorse02** [comment]
Mislim da je to ok,
Stavio bi da klikom na neki workout se prvo previewa workout, a onda ima gumb za promjenu workouta
Kalendar bi napravio tako da svaki datum workouta dovodi do jednog layouta u kojem se pregleda workout tog dana i takoder se moze promijeniti workout (u slucaju ako smo napravili neku drugu vjezbu koja ne ide u neki od ovih workouta), oznacavanjem datuma misem stvara preview za workout tog dana

**Comment by JuricaRT** [comment]
Moze, to cemo kasnije sve dodat
