### ISSUE TITLE
Calories Notes Layout

### ISSUE THREAD

**Issue by JuricaRT** [JuricaRT/fitness_tracker#14]
![Da580f29804c7202d36c5cc0f5cb28d8f](https://user-images.githubusercontent.com/57286068/91663521-a6816980-eae9-11ea-84fd-38b969813ff7.png)

- Prvi graf bi bio nesto tipa kao sto je ovaj dolje, znaci za taj odredeni dan
![1672](https://user-images.githubusercontent.com/57286068/91663538-c6b12880-eae9-11ea-99ff-244013a47fbe.jpg)

- drugi graf bi prikazivao dugorocni napredak, koje dane je korisnik dostigao calorie goal i sl.

- korisnik se moze kretati ovim strelicama u gornjem lijevo i desnom kutu tablice, one pomicu za +1 ili -1 dan

- klik na Add Food, otvara prozor sa search barom koji pretrazuje hranu u bazi

- u quick viewu ima gumb Calendar, koji bi prikazao kalendar na main panelu i pomocu tog kalendara korisnik bi mogao odabrati odredeni dan, tjedan i sl.

**Comment by afrohorse02** [comment]
Ime panela promijenit mozda u nesto bolje, kao nutrition/diet, dodat preporucen unos proteina na bazi tjelesne mase za rast misica?, dodat search bar za hranu gdje nije add food? (tako da korisnik moze provjerit hranjive vrijednosti hrane iz baze)

**Comment by JuricaRT** [comment]
![Da580f29804c7202d36c5cc0f5cb28d8f (1)](https://user-images.githubusercontent.com/57286068/91687676-9bb5eb80-eb60-11ea-91e0-e2b21ecae599.png)

- ime -> Nutrition

- u quick viewu je opcija za kalendar, kad se odabere na main panelu se prikazuje kalendar, korisnik moze odabrati odredeni dan, nakon sto odabere na main panelu se prikazuje notes layout za taj neki dan

- u quick viewu se moze odabrat Food Database, to ce pokazat na main panelu taj layout

- nakon sto korisnik upise neki pojam i stisne enter na main panelu ce se prikazati ovaj search results layout sa slikama i imenima hrane 

- korisnik moze kliknuti na neku hranu, na main panelu se zatim prikazuje layout za tu odredenu hranu

### Food Layout
- kod tog layouta gore lijevo je slika te hrane

- desno je nekakva glavna značajka, recimo kod jaja "High Protein" ili kod recimo avokada "High Potassium, Healthy Fats"

- u donjem lijevi kutu bi bio nekakav recept recimo za ova Scrambled Eggs, npr. sastojci i neki kratki opis pripreme, to mozemo nac ovdje https://www.allrecipes.com/recipes/ ili na slicnim stranicama

- u donjem desnom kutu je nutritivna tablica, mislim da je najbolje da to bude vec postojeca odnosno da stavimo sliku tablice za neku hranu kao sto je ova:
![Egg-Nutrition_Label-e1405012483980](https://user-images.githubusercontent.com/57286068/91688343-0d426980-eb62-11ea-9d05-7fc87b6f39d9.jpg)

- za neka jela za koja nema takva tablica mozemo napravit tablicu ili mozemo za sve napravit tablicu

- podatke od nekih jela mozemo nac ovdje: https://ndb.nal.usda.gov/ndb/search/list?qlookup=01132 ili na slicnim stranicama

**Comment by afrohorse02** [comment]
To je ok, mozda jedino samo da find food ne bude radio button nego button i dodat opciju za vlastitu hranu
