### ISSUE TITLE
Strength Estimator

### ISSUE THREAD

**Issue by JuricaRT** [JuricaRT/fitness_tracker#15]
Za ovaj strength estimator, ti si mislio nesto kao ovakav kalkulator https://strengthlevel.com/ ?

**Comment by afrohorse02** [comment]
Da, tak nekak

**Comment by JuricaRT** [comment]
![D00c89548e2601ec96d50f573e53628c2](https://user-images.githubusercontent.com/57286068/91842740-de58f000-ec54-11ea-8c01-6002a1f2e7f7.png)

Dolje je ona tablica kao sto je ova https://strengthlevel.com/strength-standards/deadlift
Neznam kaj bi u quick view islo
Imas jos neke ideje za dodat nesto/izmjenit ili je ovo za sad ok?
