### ISSUE TITLE
Homepage ideas

### ISSUE THREAD

**Issue by JuricaRT** [JuricaRT/fitness_tracker#2]
![ef52e7ab1f6d47c39b5571e385c50c1b](https://user-images.githubusercontent.com/57286068/90982596-60b42680-e568-11ea-9cb4-b3259b2c504f.png)

Used [https://www.mockflow.com/](url)

**Comment by JuricaRT** [comment]
![Db41f0d1012a755fc1907593f3857dc36](https://user-images.githubusercontent.com/57286068/90984394-e211b600-e574-11ea-96bb-5556746896b5.png)

**Comment by afrohorse02** [comment]
![Layout](https://user-images.githubusercontent.com/61162442/91047668-bc3eec80-e61a-11ea-83e6-a6ca143e0cfb.PNG)
Fokus na veliki panel

**Comment by JuricaRT** [comment]
![Db41f0d1012a755fc1907593f3857dc36](https://user-images.githubusercontent.com/57286068/91050864-923bf900-e61f-11ea-8cf7-f5bd20cb7759.png)

Moze ovako nesto?
