### ISSUE TITLE
Nutrition notes tablica

### ISSUE THREAD

**Issue by afrohorse02** [JuricaRT/fitness_tracker#23]
Osnovna ideja tablice je ustvari "planer" za obroke. Može se složiti plan obroka za trenutni tjedan (od ponedjeljka do nedjelje), prošli tjedan i sljedeći tjedan. Svakih tjedan dana sadržaj prošlog tjedna se briše, ovaj tjedan postaje prošli tjedan i sljedeći tjedan postaje ovaj tjedan, a sljedeći tjedan se isto briše. Manage meals omogućuje mijenjanje obroka tijekom dana (npr. doručak, ručak, užina, večera). U tablicu se može dodati namirnica ili neko jelo (ako spoonacular ima standardne porcije onda ili po standardnim porcijama ili količini u gramima).

**Comment by JuricaRT** [comment]
> Može se složiti plan obroka za trenutni tjedan (od ponedjeljka do nedjelje), prošli tjedan i sljedeći tjedan.

Misliš ovdje na trenutni i sljedeći tjedan? Ili hoćeš baš da se može i za prošli tjedan složiti plan obroka? Ova druga varijanta mi nema baš smisla jer zašto bi slagao plan obroka za prošli tjedan?

> Svakih tjedan dana sadržaj prošlog tjedna se briše, ovaj tjedan postaje prošli tjedan i sljedeći tjedan postaje ovaj tjedan, a sljedeći tjedan se isto briše

Ako sam dobro shvatio, nakon svakog tjedna briše se prošli, i dogodi se ovaj pomak, ovaj tjedan postaje prošli, a sljedeći postaje trenutni tjedan?

> Manage meals omogućuje mijenjanje obroka tijekom dana (npr. doručak, ručak, užina, večera).

Možeš još malo pojasnit ovaj Manage meals? Ako sam dobro shvatio tu misliš kao da se može uređivati recimo jela ili namirnice koje si unio za današnji dorukčak? Koje još promjene bi mogao raditi u manage meals? (tu mislim na tipa brisanje, uređivanje količine i sl.)

> U tablicu se može dodati namirnica ili neko jelo (ako spoonacular ima standardne porcije onda ili po standardnim porcijama ili količini u gramima).

Namirnice možeš searchat u gramima, a baš jela i recepte ne možeš nego imaš određenu količinu kolko je porcija u gramima.
Tu će biti neki search bar prilikom odabira namirnica koje će korisnik stavit u tablicu?
Jel možeš navest neke parametre kojima će se korisnik moći služiti prilikom pretrage namirnica? Tipa sortiraj po kalorijama ili pretraga po tome koja namirnica se nalazi u nekom receptu. Za što se sve može koristit prilikom pozivanja API-a možeš pogledat funkcije koje sam napravio ili dokumentaciju na njihovoj stranici

**Comment by afrohorse02** [comment]
> Misliš ovdje na trenutni i sljedeći tjedan? Ili hoćeš baš da se može i za prošli tjedan složiti plan obroka? Ova druga varijanta mi nema baš smisla jer zašto bi slagao plan obroka za prošli tjedan?

Ovo prošli tjedan zamijeni sa prošlih 8 tjedana, mislim da bi tako bilo bolje. Dozvoljeno je slaganje jelovnika za sve dane koje nisu prošli. Mislim da nije potrebno korisniku veća povijest jela od proteklih 8 tjedana.

 
> Ako sam dobro shvatio, nakon svakog tjedna briše se prošli, i dogodi se ovaj pomak, ovaj tjedan postaje prošli, a sljedeći postaje trenutni tjedan?

Dobro si shvatio, samo si prošlost proširi na 8 tjedana.

> Možeš još malo pojasnit ovaj Manage meals? Ako sam dobro shvatio tu misliš kao da se može uređivati recimo jela ili namirnice koje si unio za današnji dorukčak? Koje još promjene bi mogao raditi u manage meals? (tu mislim na tipa brisanje, uređivanje količine i sl.)

To mislim kao na jela dana. Sama jela će se direktno upisivat u tablicu. Ovo ustvari je parametar koliko će stupaca tablica imati u kojoj će se dodavati namirnice ili jela. Primjerice u tome korisnik može staviti da su mu jela dana: Breakfast, 12 AM snack, Lunch, 17 PM snack, Dinner. Možda to nekom drugom korisniku ne odgovara pa si može slobodno odabrati slijed kao: Lunch, Post-Workout, Dinner, Late Snack.

> Namirnice možeš searchat u gramima, a baš jela i recepte ne možeš nego imaš određenu količinu kolko je porcija u gramima.
Tu će biti neki search bar prilikom odabira namirnica koje će korisnik stavit u tablicu?
Jel možeš navest neke parametre kojima će se korisnik moći služiti prilikom pretrage namirnica? Tipa sortiraj po kalorijama ili pretraga po tome koja namirnica se nalazi u nekom receptu. Za što se sve može koristit prilikom pozivanja API-a možeš pogledat funkcije koje sam napravio ili dokumentaciju na njihovoj stranici

Malo sam pogledo, onda mislim da je najbolje po gramima količinu namirnice ili jela dodavati.
Za pretraživanje mislim da bi bilo dobro imati combobox koji ti daje mogućnost da pretraživaš ovisno o namirnici, kalorijama, masti, ugljikohidratima i proteinima. Ako se ne varam, mislim da se može simultano pretraživati namirnice i jela pa bi to tako osmislio. Dodao bi i osnove opcije sortiranje (A-Z i Z-A, najmanja količina neke hranjive vrijednosti, najveća količina hranjive vrijednosti...).
