### ISSUE TITLE
Weight loss

### ISSUE THREAD

**Issue by afrohorse02** [JuricaRT/fitness_tracker#24]
Weight loss je podijeljen na dva dijela.

Prvi dio se odnosi na sami weight loss. Korisnik može mijenjati svoju masu i program će to prepoznati kao promjena te će spremiti današnji datum i upisani rezultat u bazu. Graf će prikazivati ovisnost promjene mase s vremenom. Moći će se gledati mjesečna promjena, promjena u godini i promjena kroz više godina. Stavke će se moći mijenjati u skočnom prozoru history pod weight loss kategorijom. Korisnik će imati mogućnost promjenu datuma i promjenu same mase.

Drugi dio su cardio notes, slično izvedene kao weight loss. Korisnik će moći odabrati svoju preferiranu aktivnost. Ta se promjena mijenja u povijesti (npr. Changed Preferred Activity to Running 22.3.2021.). Korisnik će moći upisati vrijeme koje je proveo radeći preferiranu aktivnost i koliko je metara otputovao. Te se promjene sve spremaju u bazu na sljedeći način. Sve promjene koje su se promjenile na određeni datum (primjer. 22.3.2021.) spremit će se pod istom stavkom (izgledat će nešto kao 22.3.2021 : Running : 26 minutes : 2243m : Burnt 250kcal). Calories burnt će moći korisnik sam upisati ili će moći izračunati, samo što će aplikacija uzimati prosjek trajanja aktivnosti i otputovane distance. Korisnik kao i kod weight loss, moći će mijenjati i vidjeti stavke u skočnom prozoru history pod cardio notes kategorijom.

**Comment by JuricaRT** [comment]
> Graf će prikazivati ovisnost promjene mase s vremenom. Moći će se gledati mjesečna promjena, promjena u godini i promjena kroz više godina.

Ja bih ovo napravio slično kao i kod Compound Lifts, korisnik može odabrati godinu, i za ta godinu pregledava grafove koji prikazuju promjenu kilaže za odabrani mjesec.

Ovo sve ostalo je ok, ti si već napravio taj dizajn u aplikaciji? Mogu ja počet radit taj layout i ovu funkcionalnost dok ti radis nutrition. Ak si već napravio pushaj te promjene, a ak ne poslao si mi dizajn ja mislim pa ako je to taj mogu ga onda počet radit.

**Comment by afrohorse02** [comment]
Samo sam ti poslao dizajn, nisam u aplikaciji napravio. Jesam ti poslao dizajn, ak hoćeš bolju sliku mogu stavit ovdje sliku dizajna.

**Comment by JuricaRT** [comment]
Može stavit tu to kaj si napravio

**Comment by afrohorse02** [comment]
![ddddd](https://user-images.githubusercontent.com/61162442/111967085-e9dc0d80-8af7-11eb-98ea-67283da27cd0.PNG)
