### ISSUE TITLE
Workouts design

### ISSUE THREAD

**Issue by afrohorse02** [JuricaRT/fitness_tracker#25]
![workouts1 5](https://user-images.githubusercontent.com/61162442/113506831-5ec33480-9547-11eb-8d93-619164797df8.PNG)
![workouts1](https://user-images.githubusercontent.com/61162442/113506833-5ff46180-9547-11eb-9ae7-bb42e4a95780.PNG)
![workouts2](https://user-images.githubusercontent.com/61162442/113506834-608cf800-9547-11eb-8f32-216e873aa225.PNG)

**Comment by JuricaRT** [comment]
- Možeš mi pojasnit na koji način će ova dva panela biti povezani? Treba napraviti nekakvu navigaciju između njih i na koji način?
- Pretpostavljam da je ovaj drugi "glavni", ima li kalendar neke dodatne funkcionalnosti ili ne? Koliko sam skuzio moze se kliknuti 
  na pojedini dan pa se onda ovisno o tome na koji si dan kliknuo otvaraju podaci u ovom donjem lijevom dijelu?
- Kad kliknes na gumb Change pod Workout Done, otvara se prozor za odabir korisnikovih workouta? Tu se može odabrati samo jedan workout za taj dan?
- Personal notes se spremaju za svaki dan posebno ili su one iste za svaki dan?
- 1 Time workout može biti samo jedan? On se u principu briše kada prođe taj dan za koji je izrađen?

**Comment by afrohorse02** [comment]
> Možeš mi pojasnit na koji način će ova dva panela biti povezani? Treba napraviti nekakvu navigaciju između njih i na koji način?

To je osmišljeno da budu dva odvojena panela kojima se može pristupiti preko side panela. Panel za 2. sliku je "Exercises and Workouts", a za 3. sliku je "Workout Planner". Exercises dio nije bas povezan s ostatkom nego služi da korisnik može pretražiti vježbe slično kao food database s hranom. 

> Pretpostavljam da je ovaj drugi "glavni", ima li kalendar neke dodatne funkcionalnosti ili ne? Koliko sam skuzio moze se kliknuti
na pojedini dan pa se onda ovisno o tome na koji si dan kliknuo otvaraju podaci u ovom donjem lijevom dijelu?

Workout details i taj dio u donjem lijevom kutu se mijenja ovisno na kojem si danu u kalendaru. Svakom danu će se moć dodijeliti jedan od workouta koje imamo već spremljeno ili se može napraviti 1 Time Workout. Workout details su detalji za workout koji će korisnik odraditi za taj dan.

> Kad kliknes na gumb Change pod Workout Done, otvara se prozor za odabir korisnikovih workouta? Tu se može odabrati samo jedan workout za taj dan?

Da i da, ovo None je samo ako korisnik nije odabrao nijedan workout, što je ujedno i default za svaki dan.

Personal notes su posebni za svaki dan.

> 1 Time workout može biti samo jedan? On se u principu briše kada prođe taj dan za koji je izrađen?

To je tu jer sam mislio ako korisnik radi neki drugačiji workout za taj dan, da ne mora ići u Workouts panel napraviti novi workout, nego da se pojavi skočni prozor koji je sličan 1. slici i tamo korisnik kreira workout za taj dan. Kad korisnik napravi taj 1 time workout, Workout Done postaje taj kreirani 1 time workout i on se samo tamo sprema. Korisnik može teoretski za svaki dan napraviti 1 time workout, ali se on neće spremiti pod My Workouts. Također kad korisnik promijeni workout za taj dan, 1 time workout nestaje.
