### ISSUE TITLE
Color Palettes

### ISSUE THREAD

**Issue by JuricaRT** [JuricaRT/fitness_tracker#7]

**Comment by afrohorse02** [comment]
https://coolors.co/343434-2f3061-0e34a0-5f5980-dfdfdf
https://coolors.co/a31621-fcf7f8-ced3dc-4e8098-90c2e7
https://coolors.co/020300-36311f-59544b-7d8ca3-79a9d1
https://coolors.co/0a0908-22333b-f2f4f3-a9927d-5e503f
