### ISSUE TITLE
One Rep Max Calculator Layout

### ISSUE THREAD

**Issue by JuricaRT** [JuricaRT/fitness_tracker#8]
![D3398dc8431f3849943b70a84e962ab9b](https://user-images.githubusercontent.com/57286068/91398600-b0cb0b80-e83c-11ea-8294-e7c40c7f7323.png)

**Comment by afrohorse02** [comment]
Fali calculate gumb, maknut quick view na tom panelu, na prazan prostor staviti set/weight graf?

**Comment by JuricaRT** [comment]
Znaci da maknem samo ovaj quick view, a units da ostavim? Jel bi mozda nesto drugo stavili umjesto quick viewa? Ne kuzim bas kakav bi taj graf bio.

**Comment by afrohorse02** [comment]
Mozda da se quick view stavi u main panel ispod units a da units budu umjesto quick view. Jer se ne mogu sjetit kj bi uopce stavio umjesto quick viewa na tom panelu. Graf sam skuzil da nema smisla, mozda da se stavi ona tablica estimated reps at percent of 1rm

**Comment by JuricaRT** [comment]
Razmislit cu jos za ovaj quick view kaj bi moglo ic umjesto njega, ako se necu sjetit onda cu ga samo maknut i ostavit units. Mislim da nece trebat graf jer sad radim main panelu i nema bas praznog prostora a i brijem da nije potrebno.
